name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y libssl-dev libmbedtls-dev protobuf-compiler libprotobuf-c-dev libsdl2-dev libprotobuf-dev

    # run bootstrap
    - name: Bootstrap
      run: cargo build

    - name: Run tests
      run: cargo test